# Generated by Django 4.1.7 on 2024-02-24 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlogin',
            name='is_user',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='Entries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signed', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('design', models.ImageField(upload_to='uploads')),
                ('from_name', models.ForeignKey(limit_choices_to={'is_user': False}, on_delete=django.db.models.deletion.CASCADE, related_name='from_entries', to='api.userlogin')),
                ('to_name', models.ForeignKey(limit_choices_to={'is_user': True}, on_delete=django.db.models.deletion.CASCADE, related_name='to_entries', to='api.userlogin')),
            ],
        ),
    ]
